// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-KoiYTd4gpG8QJpDYXEnlMpUB-9ScWik',
    appId: '1:9159760125:web:7362bea70a3d0d08a54694',
    messagingSenderId: '9159760125',
    projectId: 'appetit-d05d5',
    authDomain: 'appetit-d05d5.firebaseapp.com',
    storageBucket: 'appetit-d05d5.firebasestorage.app',
    measurementId: 'G-RVJVL4TKRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmzSH1v4MhA9d2ITLawbpEEN-SDcuGQ4',
    appId: '1:9159760125:android:f3a9fc54da05da14a54694',
    messagingSenderId: '9159760125',
    projectId: 'appetit-d05d5',
    storageBucket: 'appetit-d05d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwzKUEzgApX0R1Ug7lUiz-ZwQG2qX0CoU',
    appId: '1:9159760125:ios:c0d01a0e202421cda54694',
    messagingSenderId: '9159760125',
    projectId: 'appetit-d05d5',
    storageBucket: 'appetit-d05d5.firebasestorage.app',
    iosBundleId: 'com.example.appetitAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwzKUEzgApX0R1Ug7lUiz-ZwQG2qX0CoU',
    appId: '1:9159760125:ios:c0d01a0e202421cda54694',
    messagingSenderId: '9159760125',
    projectId: 'appetit-d05d5',
    storageBucket: 'appetit-d05d5.firebasestorage.app',
    iosBundleId: 'com.example.appetitAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-KoiYTd4gpG8QJpDYXEnlMpUB-9ScWik',
    appId: '1:9159760125:web:d2382c713648a726a54694',
    messagingSenderId: '9159760125',
    projectId: 'appetit-d05d5',
    authDomain: 'appetit-d05d5.firebaseapp.com',
    storageBucket: 'appetit-d05d5.firebasestorage.app',
    measurementId: 'G-LXT37FSFBW',
  );
}
